version: "3.8"
services:
  elasticsearch:
    container_name: "elasticsearch-deck"
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.0"
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - elastic
  kibana:
    container_name: "kibana_deck"
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-deck:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
networks:
  elastic:
    driver: bridge
